# MySQL Configuration
spring:
  datasource:
    uri: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    h2:
      console:
        enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
# Disable H2 console and other H2 related properties
  h2:
    console:
      enabled: false
      
build:
  version: 2.0
accounts:
  message: "Welcome to accounts microservices in QA-webhook environment."
  contactDetails:
    name: "Gokil TS"
    email: "{cipher}fcaf077f6774ee0829a1f0d582e11b57cf6de36af6c07c9018b46983479877b38ee624eaceb2f4957c354b9e3701728c"
  onCallSupport:
    - (555) 567 8901
    - (555) 588 6754
