# H2 Configuration
spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: dev
    password: dev
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
build:
  version: 1.0
accounts:
  message: "Welcome to accounts microservices in dev environment."
  contactDetails:
    name: "Kannan TS"
    email: "{cipher}c66e2b18828a951734c4a143cd62adadac0eb1aaf172f0ea900b2ee00601b0c3d8131e9a7ea848e43f112d6dc5744400"
  onCallSupport:
    - (555) 567 8901
    - (555) 588 6754
